services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ivanren
      MYSQL_PASSWORD: ivanren
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
