spring:
  application:
    name: ivern-chat-app
  datasource:
    url: jdbc:mysql://localhost:3306/chatdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ivanren
    password: ivanren
  sql:
    init:
      mode: always
